<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<meta name="format-detection" content="telephone=no">';
echo '<meta name="description" content="BRM provides complete residential and commercial repair, building and maintenance. We offer garage doors, drywall, painting, wood repair, roofing and siding repair and all sorts of remodeling. From wood repairs to handyman honey do lists.">';
echo '<meta name="title" content="BRM Contractors Inc - Home">';
echo '<meta name="url" content="https://www.brmcontractors.net" />';
echo '<meta name="site_name" content="BRM Contractors Inc" />';
echo '<meta name="type" content="website" />';
echo '<meta name="robots" content="index,follow">';
echo '<meta name="googlebot" content="index,follow">';
echo '<meta name="keywords" content="BRM, McGee, handyman, home repair, Pittsburgh, Greensburg, Latrobe, Western PA, PA, Pennsylvania, improvement, contractor,';
echo 'flooring, roofing, Industrial, Commercial, Residential, New Construction, siding, tile, yardwaste, debris, concrete, bathroom, window, door, rubbish, trash,  dirt, projetcs,';
echo 'metal, wood, cleanup, garbage removal, hauling, installation, trash removal, garage door, garage opener " />';
echo '';
echo '<title>BRM Contractors | Home</title>';
echo '';
echo '<link rel="canonical" href="https://www.brmcontractors.net/" />';
echo '<link rel="icon" href="favicon.ico"/>';
echo '';
echo '<!-- Latest compiled and minified CSS -->';
echo '<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">';
echo '<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"crossorigin="anonymous"></script>';
echo '';
echo '<!-- font awesome -->';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" crossorigin="anonymous">';
echo '';
echo '<!-- local style sheet by brm  -->';
echo '<link rel="stylesheet" href="assets/css/style.css" type="text/css">';
echo '';
echo '<style>body{max-width:1400px;}</style>';
echo '</head>';
echo '<body>';
echo '';
echo '<!-- nav-bar -->';
echo '<div class="nav-bar col-12" id="navBar">';
echo '<!-- =========  NAVBAR ==========  -->';
echo '<nav class="navbar navbar-expand-lg navbar-light bg-main">';
echo '<a class="navbar-brand" href="#">';
echo '<i class="fa-solid fa-home h2 pt-2 ps-2"></i>';
echo '</a>';
echo '<a class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">';
echo '<span class="menu-icon" onclick="iconSwap(this)">';
echo '<div class="menu-icon">';
echo '<div class="bar1"></div>';
echo '<div class="bar2"></div>';
echo '<div class="bar3"></div>';
echo '</div>';
echo '</span>';
echo '</a>';
echo '';
echo '<div class="collapse navbar-collapse" id="navbarSupportedContent">';
echo '<ul class="navbar-nav mr-auto">';
echo '<li class="nav-item active">';
echo '<a class="nav-link" href="index.html">Home <span class="sr-only"></span></a>';
echo '</li>';
echo '';
echo '<li class="nav-item dropdown">';
echo '<a class="nav-link dropdown-toggle" href="about/index.html" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">';
echo 'About Us';
echo '</a>';
echo '<div class="dropdown-menu" aria-labelledby="navbarDropdown">';
echo '<a class="dropdown-item"  href="about/index.html">Info - About</a>';
echo '<a class="dropdown-item" href="contact-brm/index.html">Contact BRM</a>';
echo '<a class="dropdown-item" href="blogs/index.html">Blogs</a>';
echo '<a class="dropdown-item" href="https://www.brmnow.com/guest.php">Boxcar - Social Media</a>';
echo '</div>';
echo '</li>';
echo '<li class="nav-item dropdown">';
echo '<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">';
echo 'Services';
echo '</a>';
echo '<div class="dropdown-menu" aria-labelledby="navbarDropdown">';
echo '<a class="dropdown-item" href="services/index.html">Services</a>';
echo '<div class="dropdown-divider"></div>';
echo '<a class="dropdown-item" href="#">';
echo '<button type="button"  class="btn-solid" data-toggle="modal" data-target="#exampleModalCenter">Schedule</button>';
echo '</a>';
echo '</div>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" id="lastNav" href="blogs/index.html">BRM - Blog Posts</a>';
echo '</li>';
echo '</div>';
echo '</nav>';
echo '<!-- =========  NAVBAR/END =========  -->';
echo '</div>';
echo '';
echo '<!-- ========= MASTHEAD ================ -->';
echo '<div class="masthead">';
echo '<div class="masthead-container">';
echo '<h1>Excellent Service</h1>';
echo '<h2 class="">Home repair, installations and more <br> BRM is at your service!</h2>';
echo '<a href="https://blog.brmnow.com/view.php?q=Spring%20is%20almost%20here,%20time%20for%20home%20projects" class="btn btn-dark bg-main" >Home Repair</a>';
echo '<div class="block-text">';
echo '<p>Total home repair</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- ======= MASTHEAD END/ ============= -->';
echo '';
echo '';
echo '<!-- Page Content -->';
echo '<div class="container">';
echo '';
echo '<!-- Portfolio Item Heading -->';
echo '<h1 class="my-4 oswald">Incredible handyman</h1>';
echo '';
echo '<!-- Portfolio Item Row -->';
echo '<div class="row">';
echo '';
echo '<div class="col-md-8">';
echo '<img class="img-fluid" src="assets/gallery/bathroom-tidy.jpg" alt="">';
echo '</div>';
echo '';
echo '<div class="col-md-4">';
echo '<h3 class="my-3 oswald">Reliable and Gauranteed Service</h3>';
echo '<p>Welcome to <strong>BRM</strong> Contractors Inc. We are a family owned and operated contracting business located in Western';
echo 'Pennsylvania. We specialize in all aspects of residential and commercial construction services. Our team of';
echo 'experienced professionals is dedicated to delivering superior results to all of our projects. We take pride';
echo 'in our work and strive to exceed expectations. At BRM Contractors Inc, we understand that a construction';
echo 'project can be daunting and requires knowledge, skill and attention to detail. We also offer services such';
echo 'as remodeling, additions and custom carpentry. We are here to help make your dreams come to life, so give';
echo 'us a call today to get started.</p>';
echo '';
echo '<h3 class="my-3 oswald">Services</h3>';
echo '<ul>';
echo '<li>Drywall repairs, installs, and painting</li>';
echo '<li>Garage door, door, and window installation</li>';
echo '<li>Bathroom remodels and home repair</li>';
echo '<li>Custom decks, fences and wood repair</li>';
echo '<li>Installations and general todo lists.</li>';
echo '<li>Painting, caulking and refinishing walls.</li>';
echo '<li>Roofing, flashing, gutter soffit and fascia.</li>';
echo '</ul>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '';
echo '<!-- Related Projects Row -->';
echo '<h3 class="my-4 oswald">Related Projects</h3>';
echo '';
echo '<div class="row">';
echo '';
echo '<div class="col-md-3 col-sm-6 mb-4">';
echo '<a href="#">';
echo '<img class="img-fluid" src="https://boxcar.site/uploads/B18ECB61-9DAF-4D7F-9A59-3B5F931D02BA.jpeg" alt="">';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-md-3 col-sm-6 mb-4">';
echo '<a href="#">';
echo '<img class="img-fluid" src="https://boxcar.site/uploads/IMG-0537.jpg" alt="">';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-md-3 col-sm-6 mb-4">';
echo '<a href="#">';
echo '<img class="img-fluid" src="https://www.brmcontractors.net/assets/gallery/custom-deck6.jpg" alt="">';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-md-3 col-sm-6 mb-4">';
echo '<a href="#">';
echo '<img class="img-fluid" src="https://www.brmcontractors.net/assets/gallery/kitchen-cabinet1.jpg" alt="">';
echo '</a>';
echo '</div>';
echo '';
echo '</div>';
echo '<!-- /.row -->';
echo '';
echo '</div>';
echo '';
echo '<footer id="footer" class="footer">';
echo '<div class="footer-content position-relative">';
echo '<div class="container">';
echo '<div class="row">';
echo '';
echo '<div class="col-lg-4 col-md-6">';
echo '<div class="footer-info">';
echo '<h3>BRM Contractors</h3>';
echo '<p>Brian McGee, Owner<br>PO Box 66<br>Hannastown, PA 15635<br><br>';
echo '<span><i class="fa-solid fa-phone fs-5 me-1" aria-hidden="true"></i></span><strong>Phone:</strong> 724-787-3758<br>';
echo '<span><i class="fa-light fa-at fs-4" aria-hidden="true"></i></span><strong>Email:</strong> <a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="1674647f7778647b7571737356717b777f7a3875797b">[email&#160;protected]</a><br>';
echo '</p>';
echo '<div class="social-links d-flex mt-3">';
echo '<a href="https://www.facebook.com/profile.php?id=100054525456256#" class="d-flex align-items-center justify-content-center"><i class="fa-brands fa-facebook" aria-hidden="true"></i></a>';
echo '<a href="/cdn-cgi/l/email-protection#71130318101f031c1216141431161c10181d5f121e1c" class="d-flex align-items-center justify-content-center"><i class="fa-solid fa-envelope" aria-hidden="true"></i></a>';
echo '<a href="http://www.brmnow.com" class="d-flex align-items-center justify-content-center"><i class="fa-solid fa-dragon" aria-hidden="true"></i></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-2 col-md-3 footer-links">';
echo '<h4>Sitemap</h4>';
echo '<ul>';
echo '<li><a href="#">Home</a></li>';
echo '<li><a href="about/index.html">About us</a></li>';
echo '<li><a href="blogs/index.html">#BRM Blog</a></li>';
echo '<li><a href="services/index.html">Services</a></li>';
echo '<li><a href="contact-brm/index.html">Connect with BRM</a></li>';
echo '';
echo '</ul>';
echo '</div>';
echo '<div class="webdesign">';
echo '<a href="#">webdesign by brian</a>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</footer>';
echo '';
echo '';
echo '<!-- modal  -->';
echo '<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">';
echo '<div class="modal-dialog modal-dialog-centered" role="document">';
echo '<div class="modal-content">';
echo '<div class="modal-header bg-main text-light">';
echo '<h5 class="modal-title" id="exampleModalLongTitle">BRM Contractors Inc</h5>';
echo '<button type="button" class="close" data-dismiss="modal" aria-label="Close">';
echo '<span class="ps-1 pe-1" aria-hidden="true"> <i class="fa-solid fa-xmark" style="font-size:28px;"></i> </span>';
echo '</button>';
echo '</div>';
echo '<div class="modal-body">';
echo '<div class="schedule-message" id="schedule">';
echo '<h5>Connect with BRM</h5>';
echo '<p>Please call the office at <strong>(724) 787-3758</strong> or send us a message with your information and we will be in contact.</p>';
echo '<a href="contact-brm.html" role="button" class="btn-solid popover-test" title="Connect with BRM Contractors Inc." data-content="Popover body content is set in this attribute.">Send BRM a Message</a>';
echo '';
echo '';
echo '';
echo '';
echo '</div>';
echo '</div>';
echo '<div class="modal-footer">';
echo '<button type="button" class="btn btn-success" data-dismiss="modal">OK</button>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- local java script  -->';
echo '<script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script src="assets/js/brm.js"></script>';
echo '<script src="assets/js/main.js"></script>';
echo '';
echo '<!-- Latest compiled and minified JS -->';
echo '<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>';
echo '<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>';
echo '<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>';
echo '';
echo '</body>';
echo '</html>';

?>